// Copyright © 2023 OpenIM. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: studentgroup/studentgroup.proto

package studentgroup

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TeacherInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeacherID     string                 `protobuf:"bytes,1,opt,name=teacherID,proto3" json:"teacherID"`
	TeacherName   string                 `protobuf:"bytes,2,opt,name=teacherName,proto3" json:"teacherName"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeacherInfo) Reset() {
	*x = TeacherInfo{}
	mi := &file_studentgroup_studentgroup_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeacherInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeacherInfo) ProtoMessage() {}

func (x *TeacherInfo) ProtoReflect() protoreflect.Message {
	mi := &file_studentgroup_studentgroup_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeacherInfo.ProtoReflect.Descriptor instead.
func (*TeacherInfo) Descriptor() ([]byte, []int) {
	return file_studentgroup_studentgroup_proto_rawDescGZIP(), []int{0}
}

func (x *TeacherInfo) GetTeacherID() string {
	if x != nil {
		return x.TeacherID
	}
	return ""
}

func (x *TeacherInfo) GetTeacherName() string {
	if x != nil {
		return x.TeacherName
	}
	return ""
}

func (x *TeacherInfo) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type StudentGroupInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GroupID          string                 `protobuf:"bytes,1,opt,name=groupID,proto3" json:"groupID"`
	GroupName        string                 `protobuf:"bytes,2,opt,name=groupName,proto3" json:"groupName"`
	ClassTeacherID   string                 `protobuf:"bytes,3,opt,name=classTeacherID,proto3" json:"classTeacherID"`     // 班主任
	ClassTeacherName string                 `protobuf:"bytes,4,opt,name=classTeacherName,proto3" json:"classTeacherName"` // 班主任姓名
	TeacherList      []*TeacherInfo         `protobuf:"bytes,5,rep,name=teacherList,proto3" json:"teacherList"`           // 教师列表
	Remark           string                 `protobuf:"bytes,6,opt,name=remark,proto3" json:"remark"`                     // 备注信息
	CreateTime       int64                  `protobuf:"varint,7,opt,name=createTime,proto3" json:"createTime"`
	CreatorUserID    string                 `protobuf:"bytes,8,opt,name=creatorUserID,proto3" json:"creatorUserID"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StudentGroupInfo) Reset() {
	*x = StudentGroupInfo{}
	mi := &file_studentgroup_studentgroup_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentGroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentGroupInfo) ProtoMessage() {}

func (x *StudentGroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_studentgroup_studentgroup_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentGroupInfo.ProtoReflect.Descriptor instead.
func (*StudentGroupInfo) Descriptor() ([]byte, []int) {
	return file_studentgroup_studentgroup_proto_rawDescGZIP(), []int{1}
}

func (x *StudentGroupInfo) GetGroupID() string {
	if x != nil {
		return x.GroupID
	}
	return ""
}

func (x *StudentGroupInfo) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *StudentGroupInfo) GetClassTeacherID() string {
	if x != nil {
		return x.ClassTeacherID
	}
	return ""
}

func (x *StudentGroupInfo) GetClassTeacherName() string {
	if x != nil {
		return x.ClassTeacherName
	}
	return ""
}

func (x *StudentGroupInfo) GetTeacherList() []*TeacherInfo {
	if x != nil {
		return x.TeacherList
	}
	return nil
}

func (x *StudentGroupInfo) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *StudentGroupInfo) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *StudentGroupInfo) GetCreatorUserID() string {
	if x != nil {
		return x.CreatorUserID
	}
	return ""
}

type CreateStudentGroupReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupInfo     *StudentGroupInfo      `protobuf:"bytes,1,opt,name=groupInfo,proto3" json:"groupInfo"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStudentGroupReq) Reset() {
	*x = CreateStudentGroupReq{}
	mi := &file_studentgroup_studentgroup_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStudentGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStudentGroupReq) ProtoMessage() {}

func (x *CreateStudentGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_studentgroup_studentgroup_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStudentGroupReq.ProtoReflect.Descriptor instead.
func (*CreateStudentGroupReq) Descriptor() ([]byte, []int) {
	return file_studentgroup_studentgroup_proto_rawDescGZIP(), []int{2}
}

func (x *CreateStudentGroupReq) GetGroupInfo() *StudentGroupInfo {
	if x != nil {
		return x.GroupInfo
	}
	return nil
}

type CreateStudentGroupResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupInfo     *StudentGroupInfo      `protobuf:"bytes,1,opt,name=groupInfo,proto3" json:"groupInfo"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStudentGroupResp) Reset() {
	*x = CreateStudentGroupResp{}
	mi := &file_studentgroup_studentgroup_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStudentGroupResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStudentGroupResp) ProtoMessage() {}

func (x *CreateStudentGroupResp) ProtoReflect() protoreflect.Message {
	mi := &file_studentgroup_studentgroup_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStudentGroupResp.ProtoReflect.Descriptor instead.
func (*CreateStudentGroupResp) Descriptor() ([]byte, []int) {
	return file_studentgroup_studentgroup_proto_rawDescGZIP(), []int{3}
}

func (x *CreateStudentGroupResp) GetGroupInfo() *StudentGroupInfo {
	if x != nil {
		return x.GroupInfo
	}
	return nil
}

type GetStudentGroupsInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupIDs      []string               `protobuf:"bytes,1,rep,name=groupIDs,proto3" json:"groupIDs"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentGroupsInfoReq) Reset() {
	*x = GetStudentGroupsInfoReq{}
	mi := &file_studentgroup_studentgroup_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentGroupsInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentGroupsInfoReq) ProtoMessage() {}

func (x *GetStudentGroupsInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_studentgroup_studentgroup_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentGroupsInfoReq.ProtoReflect.Descriptor instead.
func (*GetStudentGroupsInfoReq) Descriptor() ([]byte, []int) {
	return file_studentgroup_studentgroup_proto_rawDescGZIP(), []int{4}
}

func (x *GetStudentGroupsInfoReq) GetGroupIDs() []string {
	if x != nil {
		return x.GroupIDs
	}
	return nil
}

type GetStudentGroupsInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupInfos    []*StudentGroupInfo    `protobuf:"bytes,1,rep,name=groupInfos,proto3" json:"groupInfos"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentGroupsInfoResp) Reset() {
	*x = GetStudentGroupsInfoResp{}
	mi := &file_studentgroup_studentgroup_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentGroupsInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentGroupsInfoResp) ProtoMessage() {}

func (x *GetStudentGroupsInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_studentgroup_studentgroup_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentGroupsInfoResp.ProtoReflect.Descriptor instead.
func (*GetStudentGroupsInfoResp) Descriptor() ([]byte, []int) {
	return file_studentgroup_studentgroup_proto_rawDescGZIP(), []int{5}
}

func (x *GetStudentGroupsInfoResp) GetGroupInfos() []*StudentGroupInfo {
	if x != nil {
		return x.GroupInfos
	}
	return nil
}

type SetStudentGroupInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupInfo     *StudentGroupInfo      `protobuf:"bytes,1,opt,name=groupInfo,proto3" json:"groupInfo"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetStudentGroupInfoReq) Reset() {
	*x = SetStudentGroupInfoReq{}
	mi := &file_studentgroup_studentgroup_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStudentGroupInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStudentGroupInfoReq) ProtoMessage() {}

func (x *SetStudentGroupInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_studentgroup_studentgroup_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStudentGroupInfoReq.ProtoReflect.Descriptor instead.
func (*SetStudentGroupInfoReq) Descriptor() ([]byte, []int) {
	return file_studentgroup_studentgroup_proto_rawDescGZIP(), []int{6}
}

func (x *SetStudentGroupInfoReq) GetGroupInfo() *StudentGroupInfo {
	if x != nil {
		return x.GroupInfo
	}
	return nil
}

type SetStudentGroupInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetStudentGroupInfoResp) Reset() {
	*x = SetStudentGroupInfoResp{}
	mi := &file_studentgroup_studentgroup_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStudentGroupInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStudentGroupInfoResp) ProtoMessage() {}

func (x *SetStudentGroupInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_studentgroup_studentgroup_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStudentGroupInfoResp.ProtoReflect.Descriptor instead.
func (*SetStudentGroupInfoResp) Descriptor() ([]byte, []int) {
	return file_studentgroup_studentgroup_proto_rawDescGZIP(), []int{7}
}

type StudentJoinGroupReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupID       string                 `protobuf:"bytes,1,opt,name=groupID,proto3" json:"groupID"`
	StudentIDs    []string               `protobuf:"bytes,2,rep,name=studentIDs,proto3" json:"studentIDs"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentJoinGroupReq) Reset() {
	*x = StudentJoinGroupReq{}
	mi := &file_studentgroup_studentgroup_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentJoinGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentJoinGroupReq) ProtoMessage() {}

func (x *StudentJoinGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_studentgroup_studentgroup_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentJoinGroupReq.ProtoReflect.Descriptor instead.
func (*StudentJoinGroupReq) Descriptor() ([]byte, []int) {
	return file_studentgroup_studentgroup_proto_rawDescGZIP(), []int{8}
}

func (x *StudentJoinGroupReq) GetGroupID() string {
	if x != nil {
		return x.GroupID
	}
	return ""
}

func (x *StudentJoinGroupReq) GetStudentIDs() []string {
	if x != nil {
		return x.StudentIDs
	}
	return nil
}

type StudentJoinGroupResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentJoinGroupResp) Reset() {
	*x = StudentJoinGroupResp{}
	mi := &file_studentgroup_studentgroup_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentJoinGroupResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentJoinGroupResp) ProtoMessage() {}

func (x *StudentJoinGroupResp) ProtoReflect() protoreflect.Message {
	mi := &file_studentgroup_studentgroup_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentJoinGroupResp.ProtoReflect.Descriptor instead.
func (*StudentJoinGroupResp) Descriptor() ([]byte, []int) {
	return file_studentgroup_studentgroup_proto_rawDescGZIP(), []int{9}
}

var File_studentgroup_studentgroup_proto protoreflect.FileDescriptor

const file_studentgroup_studentgroup_proto_rawDesc = "" +
	"\n" +
	"\x1fstudentgroup/studentgroup.proto\x12\x13openim.studentgroup\"a\n" +
	"\vTeacherInfo\x12\x1c\n" +
	"\tteacherID\x18\x01 \x01(\tR\tteacherID\x12 \n" +
	"\vteacherName\x18\x02 \x01(\tR\vteacherName\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"\xc0\x02\n" +
	"\x10StudentGroupInfo\x12\x18\n" +
	"\agroupID\x18\x01 \x01(\tR\agroupID\x12\x1c\n" +
	"\tgroupName\x18\x02 \x01(\tR\tgroupName\x12&\n" +
	"\x0eclassTeacherID\x18\x03 \x01(\tR\x0eclassTeacherID\x12*\n" +
	"\x10classTeacherName\x18\x04 \x01(\tR\x10classTeacherName\x12B\n" +
	"\vteacherList\x18\x05 \x03(\v2 .openim.studentgroup.TeacherInfoR\vteacherList\x12\x16\n" +
	"\x06remark\x18\x06 \x01(\tR\x06remark\x12\x1e\n" +
	"\n" +
	"createTime\x18\a \x01(\x03R\n" +
	"createTime\x12$\n" +
	"\rcreatorUserID\x18\b \x01(\tR\rcreatorUserID\"\\\n" +
	"\x15CreateStudentGroupReq\x12C\n" +
	"\tgroupInfo\x18\x01 \x01(\v2%.openim.studentgroup.StudentGroupInfoR\tgroupInfo\"]\n" +
	"\x16CreateStudentGroupResp\x12C\n" +
	"\tgroupInfo\x18\x01 \x01(\v2%.openim.studentgroup.StudentGroupInfoR\tgroupInfo\"5\n" +
	"\x17GetStudentGroupsInfoReq\x12\x1a\n" +
	"\bgroupIDs\x18\x01 \x03(\tR\bgroupIDs\"a\n" +
	"\x18GetStudentGroupsInfoResp\x12E\n" +
	"\n" +
	"groupInfos\x18\x01 \x03(\v2%.openim.studentgroup.StudentGroupInfoR\n" +
	"groupInfos\"]\n" +
	"\x16SetStudentGroupInfoReq\x12C\n" +
	"\tgroupInfo\x18\x01 \x01(\v2%.openim.studentgroup.StudentGroupInfoR\tgroupInfo\"\x19\n" +
	"\x17SetStudentGroupInfoResp\"O\n" +
	"\x13StudentJoinGroupReq\x12\x18\n" +
	"\agroupID\x18\x01 \x01(\tR\agroupID\x12\x1e\n" +
	"\n" +
	"studentIDs\x18\x02 \x03(\tR\n" +
	"studentIDs\"\x16\n" +
	"\x14StudentJoinGroupResp2\xcd\x03\n" +
	"\fstudentGroup\x12m\n" +
	"\x12createStudentGroup\x12*.openim.studentgroup.CreateStudentGroupReq\x1a+.openim.studentgroup.CreateStudentGroupResp\x12g\n" +
	"\x10joinStudentGroup\x12(.openim.studentgroup.StudentJoinGroupReq\x1a).openim.studentgroup.StudentJoinGroupResp\x12s\n" +
	"\x14getStudentGroupsInfo\x12,.openim.studentgroup.GetStudentGroupsInfoReq\x1a-.openim.studentgroup.GetStudentGroupsInfoResp\x12p\n" +
	"\x13setStudentGroupInfo\x12+.openim.studentgroup.SetStudentGroupInfoReq\x1a,.openim.studentgroup.SetStudentGroupInfoRespB,Z*github.com/openimsdk/protocol/studentgroupb\x06proto3"

var (
	file_studentgroup_studentgroup_proto_rawDescOnce sync.Once
	file_studentgroup_studentgroup_proto_rawDescData []byte
)

func file_studentgroup_studentgroup_proto_rawDescGZIP() []byte {
	file_studentgroup_studentgroup_proto_rawDescOnce.Do(func() {
		file_studentgroup_studentgroup_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_studentgroup_studentgroup_proto_rawDesc), len(file_studentgroup_studentgroup_proto_rawDesc)))
	})
	return file_studentgroup_studentgroup_proto_rawDescData
}

var file_studentgroup_studentgroup_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_studentgroup_studentgroup_proto_goTypes = []any{
	(*TeacherInfo)(nil),              // 0: openim.studentgroup.TeacherInfo
	(*StudentGroupInfo)(nil),         // 1: openim.studentgroup.StudentGroupInfo
	(*CreateStudentGroupReq)(nil),    // 2: openim.studentgroup.CreateStudentGroupReq
	(*CreateStudentGroupResp)(nil),   // 3: openim.studentgroup.CreateStudentGroupResp
	(*GetStudentGroupsInfoReq)(nil),  // 4: openim.studentgroup.GetStudentGroupsInfoReq
	(*GetStudentGroupsInfoResp)(nil), // 5: openim.studentgroup.GetStudentGroupsInfoResp
	(*SetStudentGroupInfoReq)(nil),   // 6: openim.studentgroup.SetStudentGroupInfoReq
	(*SetStudentGroupInfoResp)(nil),  // 7: openim.studentgroup.SetStudentGroupInfoResp
	(*StudentJoinGroupReq)(nil),      // 8: openim.studentgroup.StudentJoinGroupReq
	(*StudentJoinGroupResp)(nil),     // 9: openim.studentgroup.StudentJoinGroupResp
}
var file_studentgroup_studentgroup_proto_depIdxs = []int32{
	0, // 0: openim.studentgroup.StudentGroupInfo.teacherList:type_name -> openim.studentgroup.TeacherInfo
	1, // 1: openim.studentgroup.CreateStudentGroupReq.groupInfo:type_name -> openim.studentgroup.StudentGroupInfo
	1, // 2: openim.studentgroup.CreateStudentGroupResp.groupInfo:type_name -> openim.studentgroup.StudentGroupInfo
	1, // 3: openim.studentgroup.GetStudentGroupsInfoResp.groupInfos:type_name -> openim.studentgroup.StudentGroupInfo
	1, // 4: openim.studentgroup.SetStudentGroupInfoReq.groupInfo:type_name -> openim.studentgroup.StudentGroupInfo
	2, // 5: openim.studentgroup.studentGroup.createStudentGroup:input_type -> openim.studentgroup.CreateStudentGroupReq
	8, // 6: openim.studentgroup.studentGroup.joinStudentGroup:input_type -> openim.studentgroup.StudentJoinGroupReq
	4, // 7: openim.studentgroup.studentGroup.getStudentGroupsInfo:input_type -> openim.studentgroup.GetStudentGroupsInfoReq
	6, // 8: openim.studentgroup.studentGroup.setStudentGroupInfo:input_type -> openim.studentgroup.SetStudentGroupInfoReq
	3, // 9: openim.studentgroup.studentGroup.createStudentGroup:output_type -> openim.studentgroup.CreateStudentGroupResp
	9, // 10: openim.studentgroup.studentGroup.joinStudentGroup:output_type -> openim.studentgroup.StudentJoinGroupResp
	5, // 11: openim.studentgroup.studentGroup.getStudentGroupsInfo:output_type -> openim.studentgroup.GetStudentGroupsInfoResp
	7, // 12: openim.studentgroup.studentGroup.setStudentGroupInfo:output_type -> openim.studentgroup.SetStudentGroupInfoResp
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_studentgroup_studentgroup_proto_init() }
func file_studentgroup_studentgroup_proto_init() {
	if File_studentgroup_studentgroup_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_studentgroup_studentgroup_proto_rawDesc), len(file_studentgroup_studentgroup_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_studentgroup_studentgroup_proto_goTypes,
		DependencyIndexes: file_studentgroup_studentgroup_proto_depIdxs,
		MessageInfos:      file_studentgroup_studentgroup_proto_msgTypes,
	}.Build()
	File_studentgroup_studentgroup_proto = out.File
	file_studentgroup_studentgroup_proto_goTypes = nil
	file_studentgroup_studentgroup_proto_depIdxs = nil
}
